=== mwdchang/lightly-rusted/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/scene.schema.json",
  "title": "Ray Tracer Scene",
  "type": "object",

  "properties": {
    "description": {
      "type": "string"
    },

    "environment": {
      "$ref": "#/$defs/environment"
    },

    "point_lights": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/pointLight"
      }
    },

    "materials": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/material"
      }
    },

    "root": {
      "$ref": "#/$defs/node"
    }
  },

  "required": [
    "environment",
    "point_lights",
    "materials",
    "root"
  ],

  "$defs": {
    "vec3": {
      "type": "array",
      "items": {
        "type": "number"
      },
      "minItems": 3,
      "maxItems": 3
    },

    "scalar": {
      "type": "array",
      "items": {
        "type": "number"
      },
      "minItems": 1,
      "maxItems": 1
    },

    "environment": {
      "type": "object",
      "properties": {
        "background": {
          "$ref": "#/$defs/vec3"
        },
        "ambient_light": {
          "$ref": "#/$defs/vec3"
        },
        "camera_position": {
          "$ref": "#/$defs/vec3"
        },
        "camera_target": {
          "$ref": "#/$defs/vec3"
        }
      },
      "required": [
        "background",
        "ambient_light",
        "camera_position",
        "camera_target"
      ]
    },

    "pointLight": {
      "type": "object",
      "properties": {
        "position": {
          "$ref": "#/$defs/vec3"
        },
        "intensity": {
          "$ref": "#/$defs/vec3"
        }
      },
      "required": [
        "position",
        "intensity"
      ]
    },

    "material": {
      "type": "object",
      "properties": {
        "albedo": {
          "$ref": "#/$defs/vec3"
        },
        "shine": {
          "type": "number"
        },
        "specular": {
          "type": "number"
        }
      },
      "required": [
        "albedo",
        "shine",
        "specular"
      ]
    },

    "scaleTransform": {
      "type": "object",
      "properties": {
        "type": {
          "const": "scale"
        },
        "value": {
          "$ref": "#/$defs/vec3"
        }
      },
      "required": [
        "type",
        "value"
      ]
    },

    "translateTransform": {
      "type": "object",
      "properties": {
        "type": {
          "const": "translate"
        },
        "value": {
          "$ref": "#/$defs/vec3"
        }
      },
      "required": [
        "type",
        "value"
      ]
    },

    "rotateXTransform": {
      "type": "object",
      "properties": {
        "type": {
          "const": "rotate_x"
        },
        "value": {
          "$ref": "#/$defs/scalar"
        }
      },
      "required": [
        "type",
        "value"
      ]
    },

    "rotateYTransform": {
      "type": "object",
      "properties": {
        "type": {
          "const": "rotate_y"
        },
        "value": {
          "$ref": "#/$defs/scalar"
        }
      },
      "required": [
        "type",
        "value"
      ]
    },

    "rotateZTransform": {
      "type": "object",
      "properties": {
        "type": {
          "const": "rotate_z"
        },
        "value": {
          "$ref": "#/$defs/scalar"
        }
      },
      "required": [
        "type",
        "value"
      ]
    },

    "transform": {
      "oneOf": [
        {
          "$ref": "#/$defs/scaleTransform"
        },
        {
          "$ref": "#/$defs/translateTransform"
        },
        {
          "$ref": "#/$defs/rotateXTransform"
        },
        {
          "$ref": "#/$defs/rotateYTransform"
        },
        {
          "$ref": "#/$defs/rotateZTransform"
        }
      ]
    },

    "node": {
      "type": "object",
      "properties": {
        "transforms": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/transform"
          }
        },

        "mesh_id": {
          "type": "string"
        },

        "material_id": {
          "type": "number"
        },

        "children": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/node"
          }
        }
      }
    }
  }
}

=== mwdchang/lightly-rusted/scene01.json
{
  "description": "Scene 01",
  "environment": {
    "background": [0, 0.0, 0],
    "ambient_light": [0.2, 0.2, 0.2],
    "camera_position": [0, 0, 10],
    "camera_target": [0, 0, 0]
  },
  "point_lights": [
    {
      "position": [0, 80, 0],
      "intensity": [500.0, 500.0, 500.0]
    },
    {
      "position": [0, 5, 10],
      "intensity": [300.0, 300.0, 300.0]
    }
  ],
  "materials": [
    {
      "albedo": [0.3, 0.3, 0.3],
      "shine": 0,
      "specular": 0.0,
      "reflectivity": 0.1,
      "refraction_index": 0
    },
    {
      "albedo": [1.0, 1.0, 0.0],
      "shine": 0.0,
      "specular": 0.0,
      "reflectivity": 0.0,
      "refraction_index": 0
    },
    {
      "albedo": [0.0, 0.9, 0.9],
      "shine": 500.0,
      "specular": 0.1,
      "reflectivity": 0.2,
      "refraction_index": 0
    },
    {
      "albedo": [1.0, 0.1, 0.1],
      "shine": 400.0,
      "specular": 0.4,
      "reflectivity": 0.4,
      "refraction_index": 0
    }
  ],
  "root": {
    "children": [
      {
        "transforms": [
          { "type": "scale", "value": [50.0, 0.05, 50.0] },
          { "type": "translate", "value": [0, -5, 0] }
        ],
        "children": [
          {
            "mesh_id": "cube",
            "material_id": 0
          }
        ]
      },
      {
        "transforms": [
          { "type": "scale", "value": [13.0, 13.0, 11.0] },
          { "type": "rotate_y", "value": [0.5] },
          { "type": "rotate_x", "value": [1.3] },
          { "type": "translate", "value": [-3, 9, -18] }
        ],
        "children": [
          {
            "mesh_id": "torus",
            "material_id": 1
          }
        ]
      },
      {
        "transforms": [
          { "type": "scale", "value": [70.0, 70.0, 70.0] },
          { "type": "rotate_y", "value": [0.7]},
          { "type": "translate", "value": [-3, -2, -18] }
        ],
        "children": [
          {
            "mesh_id": "bunny",
            "material_id": 2
          }
        ]
      },
      {
        "transforms": [
          { "type": "scale", "value": [6.0, 6.0, 6.0] },
          { "type": "translate", "value": [9, -2, -16] }
        ],
        "children": [
          {
            "mesh_id": "sphere",
            "material_id": 3
          }
        ]
      }

    ]
  }
}
